#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xA4111F89BB5F58CC (coreteam@netfilter.org)
#
Name     : libnfnetlink
Version  : 1.0.1
Release  : 14
URL      : https://www.netfilter.org/projects/libnfnetlink/files/libnfnetlink-1.0.1.tar.bz2
Source0  : https://www.netfilter.org/projects/libnfnetlink/files/libnfnetlink-1.0.1.tar.bz2
Source99 : https://www.netfilter.org/projects/libnfnetlink/files/libnfnetlink-1.0.1.tar.bz2.sig
Summary  : Low-level netfilter netlink communication library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnfnetlink-lib
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32

%description
libnfnetlink - userspace library for handling of netfilter netlink messages
(C) 2001-2005 Netfilter Core Team <coreteam@netfilter.org>
===========================================================================

%package dev
Summary: dev components for the libnfnetlink package.
Group: Development
Requires: libnfnetlink-lib
Provides: libnfnetlink-devel

%description dev
dev components for the libnfnetlink package.


%package dev32
Summary: dev32 components for the libnfnetlink package.
Group: Default
Requires: libnfnetlink-lib32
Requires: libnfnetlink-dev

%description dev32
dev32 components for the libnfnetlink package.


%package lib
Summary: lib components for the libnfnetlink package.
Group: Libraries

%description lib
lib components for the libnfnetlink package.


%package lib32
Summary: lib32 components for the libnfnetlink package.
Group: Default

%description lib32
lib32 components for the libnfnetlink package.


%prep
%setup -q -n libnfnetlink-1.0.1
pushd ..
cp -a libnfnetlink-1.0.1 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492123217
export CFLAGS="$CFLAGS -Os -ffunction-sections "
export FCFLAGS="$CFLAGS -Os -ffunction-sections "
export FFLAGS="$CFLAGS -Os -ffunction-sections "
export CXXFLAGS="$CXXFLAGS -Os -ffunction-sections "
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492123217
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnfnetlink/libnfnetlink.h
/usr/include/libnfnetlink/linux_nfnetlink.h
/usr/include/libnfnetlink/linux_nfnetlink_compat.h
/usr/lib64/libnfnetlink.so
/usr/lib64/pkgconfig/libnfnetlink.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libnfnetlink.so
/usr/lib32/pkgconfig/32libnfnetlink.pc
/usr/lib32/pkgconfig/libnfnetlink.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnfnetlink.so.0
/usr/lib64/libnfnetlink.so.0.2.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libnfnetlink.so.0
/usr/lib32/libnfnetlink.so.0.2.0
